import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
// import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";

import PublicHeader from "@/components/header/PublicHeader";
import { ThemeProvider } from "@/components/theme/ThemeProvider";
import { isAuthPage, isPublicPage } from "@/lib/pathname";
import "./globals.css";

// const geistSans = Geist({
// 	variable: "--font-geist-sans",
// 	subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
// 	variable: "--font-geist-mono",
// 	subsets: ["latin"],
// });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const locale = await getLocale();
	const messages = await getMessages({ locale });

	const headersList = await headers();
	const pathname = headersList.get("x-pathname") || "/";
	const isPublicPath = isPublicPage(pathname) || isAuthPage(pathname);

	return (
		<html lang={locale} suppressHydrationWarning>
			<body
			// className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<NextIntlClientProvider messages={messages}>
						{isPublicPath && <PublicHeader />}
						{children}
					</NextIntlClientProvider>
				</ThemeProvider>

				<Analytics />
				<SpeedInsights />
			</body>
		</html>
	);
}
