name: 🌐 E2E Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      SUPABASE_PROJECT_ID: ${{ secrets.PREVIEW_SUPABASE_PROJECT_ID }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.PREVIEW_SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PREVIEW_SUPABASE_DB_PASSWORD }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    # ------------------------------------
    # Set Vercel environment to .env.local
    # ------------------------------------
    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Pull Preview Environment Variables
      run: vercel env pull .env.local --environment preview --yes --token ${{ secrets.VERCEL_TOKEN }}
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    # ------------------------------------
    # Reset Supabase Database
    # ------------------------------------
    - name: Install Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest

    - name: Link to the project
      run: supabase link --project-ref $SUPABASE_PROJECT_ID

    - name: Push Supabase Database
      run: supabase db push

    - name: Reset Supabase Database
      run: |
        # Read variables from .env.local
        export SUPABASE_PROJECT_ID=$(grep SUPABASE_PROJECT_ID .env.local | cut -d '=' -f2 | sed 's/"//g')
        export SUPABASE_DB_PASSWORD=$(grep SUPABASE_DB_PASSWORD .env.local | cut -d '=' -f2 | sed 's/"//g')
        # echo "SUPABASE_PROJECT_ID: $SUPABASE_PROJECT_ID"
        # echo "Extracted password (length only for security): ${#SUPABASE_DB_PASSWORD} characters"
        # Link to the project and reset remote database
        echo "yes" | supabase db reset --linked
        # echo "yes" | npx supabase db remote commit
        # echo "yes" | npx supabase db push
    # ------------------------------------
    # Build Next.js using cache
    # ------------------------------------
    - name: Cache Next.js build
      id: cache-build
      uses: actions/cache@v4
      with:
        path: .next/cache
        key: build-${{ github.ref_name }}-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        restore-keys: build-${{ github.ref_name }}-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Run Build
      run: pnpm build

    # ------------------------------------
    # Install Playwright using cache
    # ------------------------------------
    - name: Cache Playwright Browsers
      id: playwright-browsers-cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright/
        key: playwright-browsers-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: playwright-browsers-${{ runner.os }}-

    - name: Install Playwright Browsers
      if: steps.playwright-browsers-cache.outputs.cache-hit != 'true'
      run: pnpm exec playwright install --with-deps

    # Install only dependencies
    # Browser installation uses cache, but dependencies must be installed without using cache or the following error occurs
    # `Error: browserType.launch: Target page, context or browser has been closed`
    - name: Install Playwright dependencies
      run: pnpm exec playwright install-deps

    # ------------------------------------
    # Run Playwright tests
    # ------------------------------------
    - name: Run Playwright tests
      run: pnpm e2e

    # ------------------------------------
    # Upload report
    # ------------------------------------
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
