name: 🧪 Run migrations and reset db on Preview environment

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  actions: write # Required to call other workflows
  contents: write
  pull-requests: write

jobs:
  # Skip if no changes in apps/web
  check-web-app-changes:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check_changes.outputs.has_changes }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes in apps/web
        id: check_changes
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} HEAD)
          if echo "$CHANGED_FILES" | grep -q "^apps/web/"; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "There is a change in apps/web"
          else
            echo "No changes in apps/web, skipping migration and reset DB"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

  # Check if there have been any changes in apps/websupabase/migrations/*.
  check-paths:
    needs: check-web-app-changes
    if: needs.check-web-app-changes.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    outputs:
      should_run_migration: ${{ steps.check-migration-files.outputs.should_run_migration }}
    steps:
      - uses: actions/checkout@v4
      - name: Check if migration files were changed
        id: check-migration-files
        run: |
          # Clone the complete repository (default is shallow clone)
          git fetch --prune --unshallow

          # Check if the migration file has changed
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} HEAD | grep -E '^apps/web/supabase/migrations/' || true)
          if [ -n "$CHANGED_FILES" ]; then
            echo "Migration files were changed, should run migration"
            echo "should_run_migration=true" >> $GITHUB_OUTPUT
          else
            echo "No migration files were changed, skipping migration"
            echo "should_run_migration=false" >> $GITHUB_OUTPUT
          fi

  migration:
    needs: check-paths
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    # ------------------------------------
    # Set Vercel environment to .env.local
    # ------------------------------------
    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Pull Preview Environment Variables to apps/web/.env
      run: vercel env pull apps/web/.env --environment preview --yes --token ${{ secrets.VERCEL_TOKEN }}
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    - name: Pull Preview Environment Variables to packages/db/.env
      run: vercel env pull packages/db/.env --environment preview --yes --token ${{ secrets.VERCEL_TOKEN }}
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    # ------------------------------------
    # Build packages using cache
    # ------------------------------------
    - name: Cache Next.js build
      id: cache-build
      uses: actions/cache@v4
      with:
        path: |
          apps/web/.next/cache
          packages/db/dist
        key: build-${{ github.ref_name }}-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        restore-keys: build-${{ github.ref_name }}-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Build db package
      run: pnpm --filter @nito/db build

    # ------------------------------------
    # Run migrations
    # ------------------------------------
    - name: Install Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest

    # Use Vercel environment variables
    - name: Link to the project
      run: |
        export SUPABASE_PROJECT_ID=$(grep SUPABASE_PROJECT_ID apps/web/.env.local | cut -d '=' -f2 | sed 's/"//g')
        export SUPABASE_DB_PASSWORD=$(grep SUPABASE_DB_PASSWORD apps/web/.env.local | cut -d '=' -f2 | sed 's/"//g')
        export SUPABASE_ACCESS_TOKEN=$(grep SUPABASE_ACCESS_TOKEN apps/web/.env.local | cut -d '=' -f2 | sed 's/"//g')
        if [ -z "$SUPABASE_PROJECT_ID" ] || [ -z "$SUPABASE_DB_PASSWORD" ]; then
          echo "Error: Missing Supabase environment variables"
          exit 1
        fi
        cd apps/web && supabase link --project-ref $SUPABASE_PROJECT_ID --password $SUPABASE_DB_PASSWORD
      env:
        SUPABASE_ACCESS_TOKEN: $SUPABASE_ACCESS_TOKEN

    - name: Run migrations
      if: needs.check-paths.outputs.should_run_migration == 'true'
      run: |
        set -e
        # supabase migration up
        cd apps/web && supabase db push

    # ------------------------------------
    # Reset Supabase Database
    # ------------------------------------
    - name: Reset Supabase Database
      run: |
        set -e
        cd apps/web && echo "yes" | supabase db reset --linked

  result:
    needs: [check-paths, migration]
    runs-on: ubuntu-latest
    if: always()
    outputs:
      migration_result: ${{ steps.set-result.outputs.result }}
    steps:
      - name: Set migration result
        id: set-result
        run: |
          if [[ "${{ needs.check-paths.outputs.should_run_migration }}" == "false" ]]; then
            echo "Migration was skipped (no relevant files changed)"
            echo "result=skipped" >> $GITHUB_OUTPUT
          elif [[ "${{ needs.migration.result }}" == "success" ]]; then
            echo "Migration was successful"
            echo "result=success" >> $GITHUB_OUTPUT
          else
            echo "Migration failed or was cancelled"
            echo "result=failure" >> $GITHUB_OUTPUT
          fi

  call-e2e-test:
    needs: result
    if: always() && needs.result.outputs.migration_result != 'failure'
    uses: ./.github/workflows/e2e-test-on-preview.yml
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
