# Running the Vitest and Storybook tests together with `npx vitest run` may fail, so I separate them.

name: 📚 Storybook

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm --filter @nito/web exec playwright install chromium

      - name: Run Storybook tests
        run: pnpm --filter @nito/web test -- --project=storybook -- --no-threads
